name: tlutopia
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  image_path: "icons/app_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  fonts:
      - family: PlusJakartaSans
        fonts:
          - asset: fonts/font_regular.ttf
            weight: 200
          - asset: fonts/font_medium.ttf
            weight: 400            
          - asset: fonts/font_semibold.ttf
            weight: 500
          - asset: fonts/font_bold.ttf
            weight: 700
  assets:
    - assets/images/logo.png
    - assets/images/bg.png
    - assets/images/bg1.png
    - assets/images/bg2.png
    - assets/images/bg3.png
    - assets/images/bg4.png
    - assets/images/ft1.png
    - assets/images/ft2.png
    - assets/images/ft3.png
    - assets/images/ft4.png



